# Generated by Django 3.2 on 2024-12-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
