# Generated by Django 3.2 on 2024-12-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20241203_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.RemoveField(
            model_name='genre',
            name='title',
        ),
        migrations.RemoveField(
            model_name='title',
            name='title',
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='Название жанра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.TextField(db_index=True, default=1, max_length=256, verbose_name='Название произведения'),
            preserve_default=False,
        ),
    ]
